title: "Downtown Creedo"
email: ben@thehoyers.com
description: >-
  A social enterprise benefit corporation cultivating meaning, impact and
  community with direct trade coffee shops, co-working space, social enterprise
  accelerator and city-wide events.
url: "https://www.downtowncreedo.com"
cloudinary: "https://res.cloudinary.com/downtown-credo/image/upload"

# Build settings
markdown: kramdown
plugins:
  - jekyll-menus

collections:
  locations:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "locations"
    values:
      layout: "location"
