---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _locations
  label: Locations
  create: documents
  match: "**/*"
- type: document
  path: index.html
  label: Homepage
- type: document
  path: people.html
  label: People
- type: document
  path: _data/podcasts.yml
  label: Podcasts
- type: document
  path: catering.html
  label: Catering
- type: document
  path: coffee.html
  label: Coffee
- type: document
  path: story.html
  label: Story
- type: document
  path: wholesale.html
  label: Wholesale
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
